<template>
  <div
    class="bg-white border-r-2 sidebra transition-[width] duration-150 ease-in-out absolute left-0 xl:static overflow-hidden"
    :class="isCollapse ? 'w-0' : ' w-80 xl:w-96'"
  >
    <ul class="flex flex-col h-[90vh] overflow-y-auto">
      <VMenuItem
        v-for="(menuItem, index) in menuItems"
        :key="index"
        :item="menuItem"
      />
    </ul>
  </div>
</template>

<script setup>
const menuItems = [
  {
    text: "Application",
    slug: "application",
    href: "",
    icon: "",
    title: "Application",
    level: 0,
    children: [
      {
        text: "- Mobile",
        slug: "mobile",
        href: "",
        icon: "",
        title: "- Mobile",
        level: 1,
        children: [
          {
            text: "-- Social Media",
            slug: "social-media",
            href: "",
            icon: "",
            title: "-- Social Media",
            level: 2,
            children: [],
          },
          {
            text: "-- Security",
            slug: "security",
            href: "",
            icon: "",
            title: "-- Security",
            level: 2,
            children: [],
          },
          {
            text: "-- Project",
            slug: "project",
            href: "",
            icon: "",
            title: "-- Project",
            level: 2,
            children: [],
          },
          {
            text: "-- Hardware",
            slug: "hardware",
            href: "",
            icon: "",
            title: "-- Hardware",
            level: 2,
            children: [],
          },
          {
            text: "-- Activity",
            slug: "activity",
            href: "",
            icon: "",
            title: "- Activity",
            level: 2,
            children: [
              {
                text: "--- Social Media",
                slug: "social-media",
                href: "",
                icon: "",
                title: "--- Social Media",
                level: 3,
                children: [],
              },
              {
                text: "--- Security",
                slug: "security",
                href: "",
                icon: "",
                title: "- Security",
                level: 3,
                children: [],
              },
              {
                text: "--- Project",
                slug: "project",
                href: "",
                icon: "",
                title: "--- Project",
                level: 3,
                children: [],
              },
              {
                text: "--- Hardware",
                slug: "hardware",
                href: "",
                icon: "",
                title: "--- Hardware",
                level: 3,
                children: [],
              },
              {
                text: "--- Activity",
                slug: "activity",
                href: "",
                icon: "",
                title: "--- Activity",
                level: 3,
                children: [],
              },
              {
                text: "--- Social Media",
                slug: "social-media",
                href: "",
                icon: "",
                title: "--- Social Media",
                level: 3,
                children: [],
              },
              {
                text: "--- Security",
                slug: "security",
                href: "",
                icon: "",
                title: "- Security",
                level: 3,
                children: [],
              },
              {
                text: "--- Project",
                slug: "project",
                href: "",
                icon: "",
                title: "--- Project",
                level: 3,
                children: [],
              },
              {
                text: "--- Hardware",
                slug: "hardware",
                href: "",
                icon: "",
                title: "--- Hardware",
                level: 3,
                children: [],
              },
              {
                text: "--- Activity",
                slug: "activity",
                href: "",
                icon: "",
                title: "--- Activity",
                level: 3,
                children: [],
              },
            ],
          },
        ],
      },
      {
        text: "- Technology",
        slug: "technology",
        href: "",
        icon: "",
        title: "- Technology",
        level: 1,
        children: [],
      },
      {
        text: "- Game",
        slug: "game",
        href: "",
        icon: "",
        title: "- Game",
        level: 1,
        children: [],
      },
      {
        text: "- Software",
        slug: "software",
        href: "",
        icon: "",
        title: "- Software",
        level: 1,
        children: [],
      },
      {
        text: "- Internet",
        slug: "internet",
        href: "",
        icon: "",
        title: "- Internet",
        level: 1,
        children: [],
      },
    ],
  },
  {
    text: "Game",
    slug: "game",
    href: "",
    icon: "",
    title: "Game",
    level: 0,
    children: [],
  },
  {
    text: "News",
    slug: "news",
    href: "",
    icon: "",
    title: "News",
    level: 0,
    children: [],
  },
  {
    text: "Reviews",
    slug: "review",
    href: "",
    icon: "",
    title: "Reviews",
    level: 0,
    children: [
      {
        text: "- Social Media",
        slug: "social-media",
        href: "",
        icon: "",
        title: "--- Social Media",
        level: 1,
        children: [],
      },
      {
        text: "- Security",
        slug: "security",
        href: "",
        icon: "",
        title: "- Security",
        level: 1,
        children: [],
      },
      {
        text: "- Project",
        slug: "project",
        href: "",
        icon: "",
        title: "- Project",
        level: 1,
        children: [],
      },
      {
        text: "- Hardware",
        slug: "hardware",
        href: "",
        icon: "",
        title: "- Hardware",
        level: 1,
        children: [],
      },
      {
        text: "- Activity",
        slug: "activity",
        href: "",
        icon: "",
        title: "- Activity",
        level: 1,
        children: [],
      },
      {
        text: "- Social Media",
        slug: "social-media",
        href: "",
        icon: "",
        title: "- Social Media",
        level: 1,
        children: [],
      },
      {
        text: "- Security",
        slug: "security",
        href: "",
        icon: "",
        title: "- Security",
        level: 1,
        children: [],
      },
      {
        text: "- Project",
        slug: "project",
        href: "",
        icon: "",
        title: "- Project",
        level: 1,
        children: [],
      },
      {
        text: "- Hardware",
        slug: "hardware",
        href: "",
        icon: "",
        title: "- Hardware",
        level: 1,
        children: [],
      },
      {
        text: "- Activity",
        slug: "activity",
        href: "",
        icon: "",
        title: "- Activity",
        level: 1,
        children: [],
      },
    ],
  },
];

const props = defineProps({
  isCollapse: {
    type: Boolean,
    default: true,
  },
});

const toggleCollapse = () => {
  isCollapse.value = !isCollapse.value;
};
</script>
